# Generated by Django 5.0.3 on 2024-03-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.CharField(max_length=100)),
                ('groupId', models.CharField(max_length=100)),
            ],
        ),
    ]
